package com.cpyt.entity;
// Generated 27/06/2018 03:08:19 AM by Hibernate Tools 4.3.1



/**
 * ArmaIncautada generated by hbm2java
 */
public class ArmaIncautada  implements java.io.Serializable {


     private Integer idArmaincau;
     private Arma arma;
     private Operativo operativo;
     private String serie;
     private String descripcion;

    public ArmaIncautada() {
    }

    public ArmaIncautada(Arma arma, Operativo operativo, String serie, String descripcion) {
       this.arma = arma;
       this.operativo = operativo;
       this.serie = serie;
       this.descripcion = descripcion;
    }
   
    public Integer getIdArmaincau() {
        return this.idArmaincau;
    }
    
    public void setIdArmaincau(Integer idArmaincau) {
        this.idArmaincau = idArmaincau;
    }
    public Arma getArma() {
        return this.arma;
    }
    
    public void setArma(Arma arma) {
        this.arma = arma;
    }
    public Operativo getOperativo() {
        return this.operativo;
    }
    
    public void setOperativo(Operativo operativo) {
        this.operativo = operativo;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


