package com.cpyt.entity;
// Generated 27/06/2018 04:50:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Arma generated by hbm2java
 */
public class Arma  implements java.io.Serializable {


     private Integer idArma;
     private String marca;
     private String descripcion;
     private Set armaIncautadas = new HashSet(0);

    public Arma() {
    }

	
    public Arma(String marca, String descripcion) {
        this.marca = marca;
        this.descripcion = descripcion;
    }
    public Arma(String marca, String descripcion, Set armaIncautadas) {
       this.marca = marca;
       this.descripcion = descripcion;
       this.armaIncautadas = armaIncautadas;
    }
   
    public Integer getIdArma() {
        return this.idArma;
    }
    
    public void setIdArma(Integer idArma) {
        this.idArma = idArma;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getArmaIncautadas() {
        return this.armaIncautadas;
    }
    
    public void setArmaIncautadas(Set armaIncautadas) {
        this.armaIncautadas = armaIncautadas;
    }




}


