package com.cpyt.entity;
// Generated 27/06/2018 04:50:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Delito generated by hbm2java
 */
public class Delito  implements java.io.Serializable {


     private Integer idDeli;
     private String nombre;
     private Set denuncias = new HashSet(0);

    public Delito() {
    }

	
    public Delito(String nombre) {
        this.nombre = nombre;
    }
    public Delito(String nombre, Set denuncias) {
       this.nombre = nombre;
       this.denuncias = denuncias;
    }
   
    public Integer getIdDeli() {
        return this.idDeli;
    }
    
    public void setIdDeli(Integer idDeli) {
        this.idDeli = idDeli;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


