package com.cpyt.entity;
// Generated 27/06/2018 03:08:19 AM by Hibernate Tools 4.3.1



/**
 * Municion generated by hbm2java
 */
public class Municion  implements java.io.Serializable {


     private Integer idMunic;
     private Operativo operativo;
     private String marca;
     private String calibre;
     private int cantidad;
     private String descripcion;

    public Municion() {
    }

    public Municion(Operativo operativo, String marca, String calibre, int cantidad, String descripcion) {
       this.operativo = operativo;
       this.marca = marca;
       this.calibre = calibre;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
    }
   
    public Integer getIdMunic() {
        return this.idMunic;
    }
    
    public void setIdMunic(Integer idMunic) {
        this.idMunic = idMunic;
    }
    public Operativo getOperativo() {
        return this.operativo;
    }
    
    public void setOperativo(Operativo operativo) {
        this.operativo = operativo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getCalibre() {
        return this.calibre;
    }
    
    public void setCalibre(String calibre) {
        this.calibre = calibre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


