package com.cpyt.entity;
// Generated 27/06/2018 04:50:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operativo generated by hbm2java
 */
public class Operativo  implements java.io.Serializable {


     private Integer idOpera;
     private String tipoOpera;
     private String direccion;
     private String descripcion;
     private Date fechRegis;
     private String horaRegis;
     private Date fechHecho;
     private String horaHecho;
     private Set personaDenuncias = new HashSet(0);
     private Set armaIncautadas = new HashSet(0);
     private Set otros = new HashSet(0);
     private Set drogas = new HashSet(0);
     private Set municions = new HashSet(0);
     private Set vehiculoIncautados = new HashSet(0);

    public Operativo() {
    }

	
    public Operativo(String tipoOpera, String direccion, String descripcion, Date fechRegis, String horaRegis, Date fechHecho, String horaHecho) {
        this.tipoOpera = tipoOpera;
        this.direccion = direccion;
        this.descripcion = descripcion;
        this.fechRegis = fechRegis;
        this.horaRegis = horaRegis;
        this.fechHecho = fechHecho;
        this.horaHecho = horaHecho;
    }
    public Operativo(String tipoOpera, String direccion, String descripcion, Date fechRegis, String horaRegis, Date fechHecho, String horaHecho, Set personaDenuncias, Set armaIncautadas, Set otros, Set drogas, Set municions, Set vehiculoIncautados) {
       this.tipoOpera = tipoOpera;
       this.direccion = direccion;
       this.descripcion = descripcion;
       this.fechRegis = fechRegis;
       this.horaRegis = horaRegis;
       this.fechHecho = fechHecho;
       this.horaHecho = horaHecho;
       this.personaDenuncias = personaDenuncias;
       this.armaIncautadas = armaIncautadas;
       this.otros = otros;
       this.drogas = drogas;
       this.municions = municions;
       this.vehiculoIncautados = vehiculoIncautados;
    }
   
    public Integer getIdOpera() {
        return this.idOpera;
    }
    
    public void setIdOpera(Integer idOpera) {
        this.idOpera = idOpera;
    }
    public String getTipoOpera() {
        return this.tipoOpera;
    }
    
    public void setTipoOpera(String tipoOpera) {
        this.tipoOpera = tipoOpera;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechRegis() {
        return this.fechRegis;
    }
    
    public void setFechRegis(Date fechRegis) {
        this.fechRegis = fechRegis;
    }
    public String getHoraRegis() {
        return this.horaRegis;
    }
    
    public void setHoraRegis(String horaRegis) {
        this.horaRegis = horaRegis;
    }
    public Date getFechHecho() {
        return this.fechHecho;
    }
    
    public void setFechHecho(Date fechHecho) {
        this.fechHecho = fechHecho;
    }
    public String getHoraHecho() {
        return this.horaHecho;
    }
    
    public void setHoraHecho(String horaHecho) {
        this.horaHecho = horaHecho;
    }
    public Set getPersonaDenuncias() {
        return this.personaDenuncias;
    }
    
    public void setPersonaDenuncias(Set personaDenuncias) {
        this.personaDenuncias = personaDenuncias;
    }
    public Set getArmaIncautadas() {
        return this.armaIncautadas;
    }
    
    public void setArmaIncautadas(Set armaIncautadas) {
        this.armaIncautadas = armaIncautadas;
    }
    public Set getOtros() {
        return this.otros;
    }
    
    public void setOtros(Set otros) {
        this.otros = otros;
    }
    public Set getDrogas() {
        return this.drogas;
    }
    
    public void setDrogas(Set drogas) {
        this.drogas = drogas;
    }
    public Set getMunicions() {
        return this.municions;
    }
    
    public void setMunicions(Set municions) {
        this.municions = municions;
    }
    public Set getVehiculoIncautados() {
        return this.vehiculoIncautados;
    }
    
    public void setVehiculoIncautados(Set vehiculoIncautados) {
        this.vehiculoIncautados = vehiculoIncautados;
    }




}


