package com.cpyt.entity;
// Generated 27/06/2018 03:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String nombre) {
        this.nombre = nombre;
    }
    public Perfil(String nombre, Set usuarios) {
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


