package com.cpyt.entity;
// Generated 27/06/2018 03:08:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonaProceso generated by hbm2java
 */
public class PersonaProceso  implements java.io.Serializable {


     private Integer idPerpro;
     private PersonaDenuncia personaDenuncia;
     private String fiscal;
     private String sentencia;
     private String tiempo;
     private int NTiempo;
     private Date fechPro;
     private String horaPro;
     private Date fechaLibe;
     private String horaLibe;

    public PersonaProceso() {
    }

    public PersonaProceso(PersonaDenuncia personaDenuncia, String fiscal, String sentencia, String tiempo, int NTiempo, Date fechPro, String horaPro, Date fechaLibe, String horaLibe) {
       this.personaDenuncia = personaDenuncia;
       this.fiscal = fiscal;
       this.sentencia = sentencia;
       this.tiempo = tiempo;
       this.NTiempo = NTiempo;
       this.fechPro = fechPro;
       this.horaPro = horaPro;
       this.fechaLibe = fechaLibe;
       this.horaLibe = horaLibe;
    }
   
    public Integer getIdPerpro() {
        return this.idPerpro;
    }
    
    public void setIdPerpro(Integer idPerpro) {
        this.idPerpro = idPerpro;
    }
    public PersonaDenuncia getPersonaDenuncia() {
        return this.personaDenuncia;
    }
    
    public void setPersonaDenuncia(PersonaDenuncia personaDenuncia) {
        this.personaDenuncia = personaDenuncia;
    }
    public String getFiscal() {
        return this.fiscal;
    }
    
    public void setFiscal(String fiscal) {
        this.fiscal = fiscal;
    }
    public String getSentencia() {
        return this.sentencia;
    }
    
    public void setSentencia(String sentencia) {
        this.sentencia = sentencia;
    }
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    public int getNTiempo() {
        return this.NTiempo;
    }
    
    public void setNTiempo(int NTiempo) {
        this.NTiempo = NTiempo;
    }
    public Date getFechPro() {
        return this.fechPro;
    }
    
    public void setFechPro(Date fechPro) {
        this.fechPro = fechPro;
    }
    public String getHoraPro() {
        return this.horaPro;
    }
    
    public void setHoraPro(String horaPro) {
        this.horaPro = horaPro;
    }
    public Date getFechaLibe() {
        return this.fechaLibe;
    }
    
    public void setFechaLibe(Date fechaLibe) {
        this.fechaLibe = fechaLibe;
    }
    public String getHoraLibe() {
        return this.horaLibe;
    }
    
    public void setHoraLibe(String horaLibe) {
        this.horaLibe = horaLibe;
    }




}


