package com.cpyt.entity;
// Generated 27/06/2018 04:50:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPerso;
     private String dni;
     private String apelNomb;
     private String celular;
     private String direccion;
     private String nivelGrado;
     private String ocupacion;
     private Date fechNaci;
     private int edad;
     private String tipoPerso;
     private Set personaDenuncias = new HashSet(0);
     private Set servicioPolicials = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String dni, String apelNomb, String celular, String direccion, String ocupacion, Date fechNaci, int edad, String tipoPerso) {
        this.dni = dni;
        this.apelNomb = apelNomb;
        this.celular = celular;
        this.direccion = direccion;
        this.ocupacion = ocupacion;
        this.fechNaci = fechNaci;
        this.edad = edad;
        this.tipoPerso = tipoPerso;
    }
    public Persona(String dni, String apelNomb, String celular, String direccion, String nivelGrado, String ocupacion, Date fechNaci, int edad, String tipoPerso, Set personaDenuncias, Set servicioPolicials, Set usuarios) {
       this.dni = dni;
       this.apelNomb = apelNomb;
       this.celular = celular;
       this.direccion = direccion;
       this.nivelGrado = nivelGrado;
       this.ocupacion = ocupacion;
       this.fechNaci = fechNaci;
       this.edad = edad;
       this.tipoPerso = tipoPerso;
       this.personaDenuncias = personaDenuncias;
       this.servicioPolicials = servicioPolicials;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerso() {
        return this.idPerso;
    }
    
    public void setIdPerso(Integer idPerso) {
        this.idPerso = idPerso;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApelNomb() {
        return this.apelNomb;
    }
    
    public void setApelNomb(String apelNomb) {
        this.apelNomb = apelNomb;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNivelGrado() {
        return this.nivelGrado;
    }
    
    public void setNivelGrado(String nivelGrado) {
        this.nivelGrado = nivelGrado;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Date getFechNaci() {
        return this.fechNaci;
    }
    
    public void setFechNaci(Date fechNaci) {
        this.fechNaci = fechNaci;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getTipoPerso() {
        return this.tipoPerso;
    }
    
    public void setTipoPerso(String tipoPerso) {
        this.tipoPerso = tipoPerso;
    }
    public Set getPersonaDenuncias() {
        return this.personaDenuncias;
    }
    
    public void setPersonaDenuncias(Set personaDenuncias) {
        this.personaDenuncias = personaDenuncias;
    }
    public Set getServicioPolicials() {
        return this.servicioPolicials;
    }
    
    public void setServicioPolicials(Set servicioPolicials) {
        this.servicioPolicials = servicioPolicials;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


