package com.cpyt.entity;
// Generated 27/06/2018 04:50:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ServicioPolicial generated by hbm2java
 */
public class ServicioPolicial  implements java.io.Serializable {


     private Integer idSerpo;
     private Denuncia denuncia;
     private Persona persona;
     private Usuario usuario;
     private String condicion;
     private long costo;
     private String numBoucher;
     private Date fechSoli;
     private String horaSoli;

    public ServicioPolicial() {
    }

    public ServicioPolicial(Denuncia denuncia, Persona persona, Usuario usuario, String condicion, long costo, String numBoucher, Date fechSoli, String horaSoli) {
       this.denuncia = denuncia;
       this.persona = persona;
       this.usuario = usuario;
       this.condicion = condicion;
       this.costo = costo;
       this.numBoucher = numBoucher;
       this.fechSoli = fechSoli;
       this.horaSoli = horaSoli;
    }
   
    public Integer getIdSerpo() {
        return this.idSerpo;
    }
    
    public void setIdSerpo(Integer idSerpo) {
        this.idSerpo = idSerpo;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public long getCosto() {
        return this.costo;
    }
    
    public void setCosto(long costo) {
        this.costo = costo;
    }
    public String getNumBoucher() {
        return this.numBoucher;
    }
    
    public void setNumBoucher(String numBoucher) {
        this.numBoucher = numBoucher;
    }
    public Date getFechSoli() {
        return this.fechSoli;
    }
    
    public void setFechSoli(Date fechSoli) {
        this.fechSoli = fechSoli;
    }
    public String getHoraSoli() {
        return this.horaSoli;
    }
    
    public void setHoraSoli(String horaSoli) {
        this.horaSoli = horaSoli;
    }




}


