package com.cpyt.entity;
// Generated 27/06/2018 03:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDelito generated by hbm2java
 */
public class TipoDelito  implements java.io.Serializable {


     private Integer idTdeli;
     private int idDeli;
     private String nombre;
     private Set denuncias = new HashSet(0);

    public TipoDelito() {
    }

	
    public TipoDelito(int idDeli, String nombre) {
        this.idDeli = idDeli;
        this.nombre = nombre;
    }
    public TipoDelito(int idDeli, String nombre, Set denuncias) {
       this.idDeli = idDeli;
       this.nombre = nombre;
       this.denuncias = denuncias;
    }
   
    public Integer getIdTdeli() {
        return this.idTdeli;
    }
    
    public void setIdTdeli(Integer idTdeli) {
        this.idTdeli = idTdeli;
    }
    public int getIdDeli() {
        return this.idDeli;
    }
    
    public void setIdDeli(int idDeli) {
        this.idDeli = idDeli;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


