/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import com.cpyt.dao.DenunciaDAO;
import com.cpyt.dao.GenericDAO;
import com.cpyt.dao.UsuarioDAO;
import com.cpyt.entity.Delito;
import com.cpyt.entity.Denuncia;
import com.cpyt.entity.Modalidad;
import com.cpyt.entity.Persona;
import com.cpyt.entity.PersonaDenuncia;
import com.cpyt.entity.SubdetalleDelito;
import com.cpyt.entity.SubtipoDelito;
import com.cpyt.entity.TipoDelito;
import com.cpyt.entity.Usuario;
import dialogos.dlgRegistrarPersona;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import principal.Principal;

/**
 *
 * @author RojeruSan
 */
public class pnlRegistrarDenuncia extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    GenericDAO g = new GenericDAO();
    List<PersonaDenuncia> personaDenunciaList = new ArrayList<>();
    DefaultTableModel dtm = new DefaultTableModel();
    
    public pnlRegistrarDenuncia() {
        initComponents();
        
        cargarComboDelito();
        this.cboTipoDelito.addItem("--Seleccione--");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtFechaHecho = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHoraHecho = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtMinutoHecho = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboDelito = new javax.swing.JComboBox<>();
        cboSubTipoDelito = new javax.swing.JComboBox<>();
        cboTipoDelito = new javax.swing.JComboBox<>();
        cboSubDetalleDelito = new javax.swing.JComboBox<>();
        cboAfectado = new javax.swing.JComboBox<>();
        cboModalidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDNI = new javax.swing.JTextField();
        txtNombreApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboSituacion = new javax.swing.JComboBox<>();
        cboEstado = new javax.swing.JComboBox<>();
        btnAgregarPersona = new javax.swing.JButton();
        btnGrabarDenuncia = new javax.swing.JButton();
        btnCancelarDenuncia = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdPersona = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIdDelito = new javax.swing.JLabel();
        txtIdTipoDelito = new javax.swing.JLabel();
        txtIdSubTipoDelito = new javax.swing.JLabel();
        txtIdSubDetalleDelito = new javax.swing.JLabel();
        txtIdModa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(128, 128, 131));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Registrar Denuncia");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 86, 186));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Fecha del Hecho :");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 86, 186));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Hora del Hecho :");

        txtHoraHecho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(38, 86, 186));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Descripción :");

        txtMinutoHecho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(38, 86, 186));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Dirección :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");

        cboDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDelitoActionPerformed(evt);
            }
        });

        cboSubTipoDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubTipoDelitoActionPerformed(evt);
            }
        });

        cboTipoDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDelitoActionPerformed(evt);
            }
        });

        cboSubDetalleDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubDetalleDelitoActionPerformed(evt);
            }
        });

        cboAfectado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "BANCOS O FINANCIERAS", "BOTICAS Y FARMACIAS", "CAMBISTAS", "CENTROS EDUCATIVOS", "CENTROS COMERCIALES", "CONDUCTORES DE OTROS VEHICULOS", "DOMICILIOS", "EMPRESAS DE PRODUCCIÓN", "EMPRESAS DE SERVICIOS", "GRIFOS", "HOTELES", "INSTITUCIONES", "TAXISTAS", "TRANSEUNTES", "VEH. TRANSPORTE DE PASAJEROS", "VEHÍCULOS DISTRIBUIDORES", "VEHÍCULOS DE TRANSP. CARGA", "OTROS" }));
        cboAfectado.setEnabled(false);

        cboModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModalidadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Delito :");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 86, 186));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo de Delito :");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 86, 186));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("SubTipo Delito :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 86, 186));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Modalidad :");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 86, 186));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("SubDetalle Delito :");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 86, 186));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Afectado :");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtDNI.setOpaque(false);

        txtNombreApellidos.setEditable(false);
        txtNombreApellidos.setOpaque(false);
        txtNombreApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApellidosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Datos de la Persona");

        cboSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DENUN. Y VICT.", "DENUNCIANTE", "DENUNCIADO", "VICTIMA" }));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "CITADO", "DETENIDO", "NO HABIDO", "PENALIZADO" }));

        btnAgregarPersona.setText("AGREGAR");
        btnAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaActionPerformed(evt);
            }
        });

        btnGrabarDenuncia.setText("GRABAR");
        btnGrabarDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarDenunciaActionPerformed(evt);
            }
        });

        btnCancelarDenuncia.setText("CANCELAR");
        btnCancelarDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDenunciaActionPerformed(evt);
            }
        });

        btnBuscarPersona.setText("BUSCAR");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Personas vinculadas a la denuncia");

        tableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Apellidos y Nombres", "Situación", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tableDatos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellidos y nombres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("DNI");

        txtIdPersona.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Situación");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(596, 596, 596))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(35, 35, 35))
                                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscarPersona)
                                            .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btnAgregarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                        .addGap(351, 351, 351)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btnGrabarDenuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarDenuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtIdPersona)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPersona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarDenuncia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarDenuncia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtIdDelito.setText("0");

        txtIdTipoDelito.setText("0");

        txtIdSubTipoDelito.setText("0");

        txtIdSubDetalleDelito.setText("0");

        txtIdModa.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDelito, 0, 219, Short.MAX_VALUE)
                            .addComponent(cboSubTipoDelito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboModalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSubDetalleDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtHoraHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinutoHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDireccion)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdSubTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdSubDetalleDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIdModa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboDelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTipoDelito)
                            .addComponent(txtIdDelito))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cboSubTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSubDetalleDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdSubTipoDelito)
                            .addComponent(txtIdSubDetalleDelito))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cboAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdModa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtHoraHecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtMinutoHecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFechaHecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApellidosActionPerformed

    private void btnCancelarDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDenunciaActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlDenuncia());
    }//GEN-LAST:event_btnCancelarDenunciaActionPerformed

    private void cboDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDelitoActionPerformed
        //GenericDAO g = new GenericDAO();
        Integer idDeli = g.getIdItemSeleccionado("id_deli", "delito", "nombre", cboDelito.getSelectedItem().toString(), "");
        txtIdDelito.setText(String.valueOf(idDeli));
        
        cargarComboTipoDelito();
    }//GEN-LAST:event_cboDelitoActionPerformed

    private void cboTipoDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDelitoActionPerformed
        
        if (!cboDelito.getSelectedItem().toString().equals("--Seleccione--")) {
            
            if(!(cboTipoDelito.getSelectedItem()==null)){
               //GenericDAO g = new GenericDAO();
                Integer idTipoDeli = g.getIdItemSeleccionado("id_tdeli", "tipo_delito", "nombre", cboTipoDelito.getSelectedItem().toString(), "");
                txtIdTipoDelito.setText(String.valueOf(idTipoDeli));
                if(idTipoDeli == 23 || idTipoDeli == 24){
                    cboAfectado.setEnabled(true);
                }else{
                    cboAfectado.setEnabled(false);
                }
            }
            
        }
        
        
        cargarComboModalidad();
        cargarComboSubTipoDelito();
    }//GEN-LAST:event_cboTipoDelitoActionPerformed

    private void cboSubTipoDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubTipoDelitoActionPerformed
        if (cboTipoDelito.getSelectedItem()!=null && !cboTipoDelito.getSelectedItem().toString().equals("--Seleccione--")) {
            
            if(!(cboSubTipoDelito.getSelectedItem()==null)){
               //GenericDAO g = new GenericDAO();
                Integer idSubTipoDeli = g.getIdItemSeleccionado("id_stdelito", "subtipo_delito", "nombre", cboSubTipoDelito.getSelectedItem().toString(), "");
                txtIdSubTipoDelito.setText(String.valueOf(idSubTipoDeli)); 
            }
            
        }
        
        cargarComboSubDetalleDelito();
    }//GEN-LAST:event_cboSubTipoDelitoActionPerformed

    private void cboSubDetalleDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubDetalleDelitoActionPerformed
        if (cboSubTipoDelito.getSelectedItem()!=null && !cboSubTipoDelito.getSelectedItem().toString().equals("--Seleccione--")) {
            
            if(!(cboSubDetalleDelito.getSelectedItem()==null)){
               //GenericDAO g = new GenericDAO();
                Integer idSubDetalleDeli = g.getIdItemSeleccionado("id_sddelito", "subdetalle_delito", "nombre", cboSubDetalleDelito.getSelectedItem().toString(), "");
                txtIdSubDetalleDelito.setText(String.valueOf(idSubDetalleDeli)); 
            }
            
        }
        
    }//GEN-LAST:event_cboSubDetalleDelitoActionPerformed

    private void cboModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModalidadActionPerformed
        if (cboTipoDelito.getSelectedItem()!=null && !cboTipoDelito.getSelectedItem().toString().equals("--Seleccione--")) {
            
            if(!(cboModalidad.getSelectedItem()==null)){
               //GenericDAO g = new GenericDAO();
                Integer idModa = g.getIdItemSeleccionado("id_moda", "modalidad", "nombre", cboModalidad.getSelectedItem().toString(), "");
                txtIdModa.setText(String.valueOf(idModa)); 
            }
            
        }
    }//GEN-LAST:event_cboModalidadActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        if(txtDNI.getText().trim().equals("")){
            JOptionPane.showMessageDialog(cboEstado, "Ingrese el DNI para buscar !");
            return;
        }
        
        DenunciaDAO d = new DenunciaDAO();
        Persona persona = d.consultarPersona(txtDNI.getText());
        if(persona == null){
            JOptionPane.showMessageDialog(null, "No encontrado, tiene que registrar a la persona !");
            dlgRegistrarPersona rp = new dlgRegistrarPersona(null, true);
            rp.setVisible(true);
    
        }else{
            txtIdPersona.setText(persona.getIdPerso().toString());
            txtDNI.setText(persona.getDni());
            txtNombreApellidos.setText(persona.getApelNomb());            
        }

    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaActionPerformed
        
        Integer idPerso = Integer.parseInt(txtIdPersona.getText());
        String dni = txtDNI.getText();
        String apeNomb = txtNombreApellidos.getText();
        String situacion = cboSituacion.getSelectedItem().toString();
        String estado = cboEstado.getSelectedItem().toString();
        
        PersonaDenuncia pd = new PersonaDenuncia();
        Persona per = new Persona();
        per.setIdPerso(idPerso);
        per.setDni(dni);
        per.setApelNomb(apeNomb);
        
        pd.setPersona(per);
        pd.setSituacion(situacion);
        pd.setEstado(estado);
        
        personaDenunciaList.add(pd);
        
        txtIdPersona.setText("0");
        txtDNI.setText("");
        txtNombreApellidos.setText("");
        cboSituacion.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);
        txtDNI.requestFocus();
        
        cargarPersonasVinculadasDenuncia();
        
        
    }//GEN-LAST:event_btnAgregarPersonaActionPerformed

    private void btnGrabarDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarDenunciaActionPerformed
         //INSERT PARA PROCESO DE DENUNCIA
        try {
            
        
        Denuncia den = new Denuncia();
        
        if(!txtIdDelito.getText().equals("0")){
            Delito de = new Delito();
            de.setIdDeli(Integer.parseInt(txtIdDelito.getText()));
            den.setDelito(de);
        }
        
        
        if(!txtIdTipoDelito.getText().equals("0")){
            TipoDelito td = new TipoDelito();
            td.setIdTdeli(Integer.parseInt(txtIdTipoDelito.getText()));
            den.setTipoDelito(td);   
        }
        
        
        if(!txtIdSubTipoDelito.getText().equals("0")){
            SubtipoDelito std = new SubtipoDelito();
            std.setIdStdelito(Integer.parseInt(txtIdSubTipoDelito.getText()));
            den.setSubtipoDelito(std);
        }
        
        
        if(!txtIdSubDetalleDelito.getText().equals("0")){
            SubdetalleDelito sdd = new SubdetalleDelito();
            sdd.setIdSddelito(Integer.parseInt(txtIdSubDetalleDelito.getText()));
            den.setSubdetalleDelito(sdd);
        }
        
        
        if(!txtIdModa.getText().equals("0")){
            Modalidad m = new Modalidad();
            m.setIdModa(Integer.parseInt(txtIdModa.getText()));
            den.setModalidad(m);    
        }
          
        
        
        
        den.setFechRegis(new Date());
        den.setHoraRegis("20:50");
        den.setFechHecho(txtFechaHecho.getDate());
        den.setHoraHecho(txtHoraHecho.getSelectedItem().toString()+":"+txtMinutoHecho.getSelectedItem());
        den.setAfectado(cboAfectado.getSelectedItem().toString());
        den.setDireccion(txtDireccion.getText());
        den.setDescripcion(txtDescripcion.getText());
        
        
        
        HashSet<PersonaDenuncia> pd = new HashSet<PersonaDenuncia>();
        
        for (int i = 0; i < personaDenunciaList.size(); i++) {
            PersonaDenuncia pede = new PersonaDenuncia();
            pede = personaDenunciaList.get(i);
           pd.add(new PersonaDenuncia(pede.getPersona(), pede.getSituacion(), pede.getEstado()));
        }
        if(pd.size()>0){
            den.setPersonaDenunciaList(pd);
        }
        
        
        g.insert(den);
        //JOptionPane.showMessageDialog(null, "Denuncia Grabado Exitosamente !");
        int op = JOptionPane.showConfirmDialog(null, "Denuncia Grabado Exitosamente, ¿Desea imprimir la Denuncia?","Éxito",JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION){
            imprimirReporteDenuncia();
            new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlDenuncia());
        }else{
            new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlDenuncia());
        }
        
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al grabar la Denuncia !");
        }
        
    }//GEN-LAST:event_btnGrabarDenunciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersona;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCancelarDenuncia;
    private javax.swing.JButton btnGrabarDenuncia;
    private javax.swing.JComboBox<String> cboAfectado;
    private javax.swing.JComboBox<String> cboDelito;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboModalidad;
    private javax.swing.JComboBox<String> cboSituacion;
    private javax.swing.JComboBox<String> cboSubDetalleDelito;
    private javax.swing.JComboBox<String> cboSubTipoDelito;
    private javax.swing.JComboBox<String> cboTipoDelito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDatos;
    public static javax.swing.JTextField txtDNI;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private com.toedter.calendar.JDateChooser txtFechaHecho;
    private javax.swing.JComboBox<String> txtHoraHecho;
    private javax.swing.JLabel txtIdDelito;
    private javax.swing.JLabel txtIdModa;
    public static javax.swing.JLabel txtIdPersona;
    private javax.swing.JLabel txtIdSubDetalleDelito;
    private javax.swing.JLabel txtIdSubTipoDelito;
    private javax.swing.JLabel txtIdTipoDelito;
    private javax.swing.JComboBox<String> txtMinutoHecho;
    private javax.swing.JTextField txtNombreApellidos;
    // End of variables declaration//GEN-END:variables

    private void cargarComboDelito() {
        //GenericDAO g = new GenericDAO();
        List<Object> sad = g.getComboList("delito", "id_deli", "nombre", "");
        Object[] s = new Object[]{};
        this.cboDelito.addItem("--Seleccione--");
        for (int i = 0;i<sad.size();i++) {
            s = (Object[])sad.get(i);
            System.out.println("Id = "+s[0]);
            System.out.println("Nombre = "+s[1]);
            
            this.cboDelito.addItem(s[1].toString());
        
        }
    }

    private void cargarComboTipoDelito() {
        //GenericDAO g = new GenericDAO();
        List<Object> sad = g.getComboList("tipo_delito", "id_tdeli", "nombre", "where id_deli="+txtIdDelito.getText());
        Object[] s = new Object[]{};
        this.cboTipoDelito.removeAllItems();
        this.cboTipoDelito.addItem("--Seleccione--");
        for (int i = 0;i<sad.size();i++) {
            s = (Object[])sad.get(i);
            System.out.println("Id = "+s[0]);
            System.out.println("Nombre = "+s[1]);
            
            this.cboTipoDelito.addItem(s[1].toString());
        
        }
        boolean existe = false;
        if(sad.size()==0){
            this.cboTipoDelito.setEnabled(false);
            this.cboTipoDelito.removeAllItems();
            this.cboTipoDelito.addItem("No existe");
            txtIdTipoDelito.setText("0");
            txtIdSubTipoDelito.setText("0");
            txtIdSubDetalleDelito.setText("0");
        }else{
            this.cboTipoDelito.setEnabled(true);
        }
    }
    
    private void cargarComboSubTipoDelito() {
        //GenericDAO g = new GenericDAO();
        List<Object> sad = g.getComboList("subtipo_delito", "id_stdelito", "nombre", "where id_tdelito="+txtIdTipoDelito.getText());
        Object[] s = new Object[]{};
        this.cboSubTipoDelito.removeAllItems();
        this.cboSubTipoDelito.addItem("--Seleccione--");
        for (int i = 0;i<sad.size();i++) {
            s = (Object[])sad.get(i);
            System.out.println("Id = "+s[0]);
            System.out.println("Nombre = "+s[1]);
            
            this.cboSubTipoDelito.addItem(s[1].toString());
        
        }
        boolean existe = false;
        if(sad.size()==0){
            this.cboSubTipoDelito.setEnabled(false);
            this.cboSubTipoDelito.removeAllItems();
            this.cboSubTipoDelito.addItem("No existe");
            
            txtIdSubTipoDelito.setText("0");
            txtIdSubDetalleDelito.setText("0");
        }else{
            this.cboSubTipoDelito.setEnabled(true);
        }
    }

    private void cargarComboSubDetalleDelito() {
        //GenericDAO g = new GenericDAO();
        List<Object> sad = g.getComboList("subdetalle_delito", "id_sddelito", "nombre", "where id_stdelito="+txtIdSubTipoDelito.getText());
        Object[] s = new Object[]{};
        this.cboSubDetalleDelito.removeAllItems();
        this.cboSubDetalleDelito.addItem("--Seleccione--");
        for (int i = 0;i<sad.size();i++) {
            s = (Object[])sad.get(i);
            System.out.println("Id = "+s[0]);
            System.out.println("Nombre = "+s[1]);
            
            this.cboSubDetalleDelito.addItem(s[1].toString());
        
        }
        boolean existe = false;
        if(sad.size()==0){
            this.cboSubDetalleDelito.setEnabled(false);
            this.cboSubDetalleDelito.removeAllItems();
            this.cboSubDetalleDelito.addItem("No existe");
            
            
            txtIdSubDetalleDelito.setText("0");
        }else{
            this.cboSubDetalleDelito.setEnabled(true);
        }
    }

    private void cargarComboModalidad() {
        //GenericDAO g = new GenericDAO();
        List<Object> sad = g.getComboList("modalidad", "id_moda", "nombre", "where id_stdelito="+txtIdTipoDelito.getText());
        Object[] s = new Object[]{};
        this.cboModalidad.removeAllItems();
        this.cboModalidad.addItem("--Seleccione--");
        for (int i = 0;i<sad.size();i++) {
            s = (Object[])sad.get(i);
            System.out.println("Id = "+s[0]);
            System.out.println("Nombre = "+s[1]);
            
            this.cboModalidad.addItem(s[1].toString());
        
        }
        boolean existe = false;
        if(sad.size()==0){
            this.cboModalidad.setEnabled(false);
            this.cboModalidad.removeAllItems();
            this.cboModalidad.addItem("No existe");
        }else{
            this.cboModalidad.setEnabled(true);
        }
    }
    
    public void cargarPersonaRegistrada(){
        Integer idPerso = g.ultimoID("idPerso", "Persona");
        DenunciaDAO d = new DenunciaDAO();
        Persona perso = d.consultarPersonaPorId(idPerso);
        txtIdPersona.setText(perso.getIdPerso().toString());
        txtNombreApellidos.setText(perso.getApelNomb());
        txtDNI.setText(perso.getDni());
    }

    private void cargarPersonasVinculadasDenuncia() {
        Object[][] matriz = new Object[personaDenunciaList.size()][4];
        Object[] s = new Object[]{};
        for (int i = 0; i < personaDenunciaList.size(); i++) {
            
            matriz[i][0] = personaDenunciaList.get(i).getPersona().getDni();
            matriz[i][1] = personaDenunciaList.get(i).getPersona().getApelNomb();
            matriz[i][2] = personaDenunciaList.get(i).getSituacion();
            matriz[i][3] = personaDenunciaList.get(i).getEstado();
 
        }
        Object[][] data = matriz;
        String[] cabecera = {"DNI", "Apellidos y Nombres","Situación","Estado"};
        dtm = new DefaultTableModel(data, cabecera);
        tableDatos.setModel(dtm);
        

    }

    
    public void imprimirReporteDenuncia(){
        
        Integer idDenun = g.ultimoID("idDenun", "Denuncia");
        DenunciaDAO dd = new DenunciaDAO();
        
        Denuncia de = dd.getDenunciaPorId(idDenun);
        
        try {
            String master = System.getProperty("user.dir") ;
            //File rep=new File("src/report/report1.jasper");
            File rep=new File(master+"/src/main/java/com/cpyt/report/reportDenuncia.jasper");
            JasperReport file =(JasperReport)JRLoader.loadObject(rep);
            
            HashMap para= new HashMap();
            
            para.put("delito", de.getDelito().getNombre());
            para.put("tdelito", de.getTipoDelito().getNombre());
            if(de.getSubtipoDelito()!=null){
                para.put("stdelito", de.getSubtipoDelito().getNombre());
            }
            if(de.getSubdetalleDelito()!=null){
                para.put("sddelito", de.getSubdetalleDelito().getNombre());
            }
            if(de.getModalidad()!=null){
                para.put("modalidad", de.getModalidad().getNombre());
            }
            para.put("afectado", de.getAfectado());
            para.put("direccion", de.getDireccion());
            para.put("fecha", de.getFechHecho());
            para.put("hora", de.getHoraHecho());
            para.put("descripcion", de.getDescripcion());
            
            Set<PersonaDenuncia> pd = de.getPersonaDenunciaList();
        
            Iterator iter = pd.iterator();
            int i = 1;
            while (iter.hasNext()) {
                PersonaDenuncia ped = (PersonaDenuncia) iter.next();
                para.put("dni_"+i, ped.getPersona().getDni());
                para.put("nombre_"+i, ped.getPersona().getApelNomb());
                para.put("situacion_"+i, ped.getSituacion());
                para.put("estado_"+i, ped.getEstado());
                i++;
            } 
            
            UsuarioDAO ud = new UsuarioDAO();
            Usuario usu = ud.getUserInSession();
            para.put("usuario", usu.getPersona().getApelNomb());
            para.put("fecharegistro", new Date());
            
         
            JasperPrint jprint = JasperFillManager.fillReport(file,para,new JREmptyDataSource());
            
            JasperViewer.viewReport(jprint,false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error en la generación del documento");
        }
    }
}
